### ISSUE TITLE
保活脚本task_proc_watcher.sh在mac会一分钟启动一个进程

### ISSUE THREAD

**Issue by likaiqing** [siaorg/sia-task#10]
task_proc_watcher.sh脚本内"ps -fC java | grep $process_flag | wc -l" 此行代码在mac系统不支持"ps -fC java "。脚本run4config.sh保活功能可采用 */1 * * * * flock -xn file.lock -c ''实现

**Comment by EatApples** [comment]
> task_proc_watcher.sh脚本内"ps -fC java | grep $process_flag | wc -l" 此行代码在mac系统不支持"ps -fC java "。

（1）因为不识别 "-C" 参数，在  if 判断进程的个数时进入重启逻辑，按理说，应该一分钟重启4次。
然而因为端口占用，重启的应用会死亡，但是重启的进程暂未消亡。

解决方案：判断进程的执行逻辑改为

```
count=`ps -ef | grep java | grep $process_flag | wc -l`
```

> 脚本run4config.sh保活功能可采用 */1 * * * * flock -xn file.lock -c ''实现

（2）flock文件锁只是预防定时任务并行执行，而在保活脚本中，执行时长<60S，不会有并行执行问题。
即使并行执行了，只要判断进程的逻辑没问题，则保活脚本啥都不做。
总之，flock文件锁能解决crontab冲突问题，与保活脚本的正确性无关。
