### ISSUE TITLE
能不能支持Eureka作为注册中心

### ISSUE THREAD

**Issue by wzyxdwll** [siaorg/sia-task#15]

**Comment by EatApples** [comment]
**一句话回答就是：可以，但是没必要。**

在任务编排框架中，需要部署多个调度器来执行`Job`。

考虑到集群模式下需要满足：
+ 负载均衡
+ 预防单点故障
+ 动态扩展

对于调度器，需要使用某些机制来达到这些效果。

要想达到这些效果，应该要满足：

+ 需要使用注册中心来协调
+ 需要使用分布式锁来同步
+ 需要使用消息传递来控制

我们这里使用`Zookeeper`，满足这些条件：
+ `Zookeeper`本身就是一个目录型的资源中心，常被用作注册中心
+ `Zookeeper`集群架构是单写多读，写动作是顺序一致性，本身就提供分布式锁服务。这里使用客户端`Curator`封装好的可重入的分布式锁服务
+ `Zookeeper`本身就有异步通知机制`Watcher`，这里使用客户端`Curator`封装好的更简易的监听机制

换句话说，ZooKeeper 在任务调度中有3个作用：

（一）资源中心：存储元数据
元数据包括静态数据与动态数据。
（1）实时抓取的Task 信息（静态数据）
（2）执行器实例信息（动态数据）。调度器运行时会查询获取。
（3）Job索引信息（动态数据）。调度器通过争抢之后，抢占该Job。Job的控制（用户控制，调度器执行Job的状态等）也通过这些信息交互。
（二）提供分布式锁服务
调度器Job获取是拉（pull）模式，抢占Job时需要分布式的锁。
（三）故障转移，高可用保障
通过ZooKeeper提供的 Watcher 机制，保证 Job 的执行高可用。

注意到， （一）资源中心的角色就是注册中心，当然可以使用其他来替换，例如 Eureka。
               （二）分布式锁的服务当然也可以使用基于数据库的或基于Redis的。
               （三）至于消息通知，ETCD 也能充当该角色（未验证）。

 总的来说，zookeeper 一个能抵三个，如非必要，勿增实体。
