### ISSUE TITLE
测试job联通的时候居然报这种不支持post的错误？有点low啊

### ISSUE THREAD

**Issue by littleyang** [siaorg/sia-task#24]
{"timestamp":1559104769109,"status":405,"error":"Method Not Allowed","exception":"org.springframework.web.HttpRequestMethodNotSupportedException","message":"Request method 'POST' not supported","path":"/taskapi/connextest"}

   /**
     * front-end calls the API
     * Task connectivity test
     * For tasks that use the sia-task-hunter component and achieve automatic fetching
     * through standard annotations,sia-task-hunter adds permission control.
     * IP that is not within this permission cannot call the task.
     * If it is necessary to test whether the task can work normally (POST only)
     * @param request
     * @return
     */
    @RequestMapping(value = "/connextest", produces = "application/json;charset=UTF-8",method = RequestMethod.GET)
    @ResponseBody
    public String connexTest(@RequestBody Map<String,String> request) {
        if(request == null) {
            LOGGER.info(Constants.LOG_PREFIX +"connextest by user:"+ userService.getCurrentUser());
            return ResultBody.failed();
        }
        String param = request.get("param");
        String result;
        try {
            String url = request.get("url");
            LOGGER.info(Constants.LOG_PREFIX +"connextest by user:"+ userService.getCurrentUser());
            LOGGER.info(Constants.LOG_PREFIX + "url："+ url);
            LOGGER.info(Constants.LOG_PREFIX +"param: "+param);
            result = basicTaskService.testTask(url,param);
        } catch (Exception e) {
            LOGGER.error(Constants.LOG_PREFIX + " connexTest Error ：", e);
            return ResultBody.error();
        }
        return ResultBody.success((Object) result);
    }

最后再说多说一句：不愿意不想做开源，不要放出来好么？

**Comment by TeddiWolf** [comment]
多谢指正，sia-task-config下的类已经完成修改支持POST，其他的module我们会今天完成排查和修改。
