### ISSUE TITLE
web node 编译失败

### ISSUE THREAD

**Issue by raymondchen-byte** [siaorg/sia-task#37]
安装依赖包时提示如下错误
请问如何在windows 或者  centos下正确编译
Error making request.
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27)

Please report this full log at https://github.com/Medium/phantomjs
npm WARN The package eslint-config-standard is included as both a dev and production dependency.
npm WARN The package eslint-plugin-html is included as both a dev and production dependency.
npm WARN The package eslint-plugin-promise is included as both a dev and production dependency.
npm WARN The package eslint-plugin-standard is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.1 (node_modules/quill-image-resize-module/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by yuhuiyong88** [comment]
引起这个问题的原因有时候是网络不好造成，可以试下用cnpm  install（cnpm 安装命令-》npm install -g cnpm --registry=https://registry.npm.taobao.org）来下载依赖包这个命令不会出现网络不好而引起问题
