### ISSUE TITLE
出现异常时，页面就强制跳转回登录页面的问题

### ISSUE THREAD

**Issue by wushijing30** [siaorg/sia-task#50]
每当页面配置错误，出现异常时，页面就强制跳转回登录页面，如下图，这样又要重新输入登录，重新填写之前的配置信息，个人觉得出错了，有提示就行了，没必要跳转。
![image](https://user-images.githubusercontent.com/8540771/59907244-35521b00-943d-11e9-98ec-3d477e137cf9.png)

**Comment by TeddiWolf** [comment]
修复
