### ISSUE TITLE
提问：是否可以直接配置接口地址，触发任务调度？

### ISSUE THREAD

**Issue by fxbin** [siaorg/sia-task#67]
提问：是否可以直接配置接口地址，触发任务调度，我在本地搭建运行，找不到配置的地方

**Comment by TeddiWolf** [comment]
可以啊，开发文档里都有使用方式的描述

**Comment by fxbin** [comment]
开发文档里只有 自动抓取任务开发规则 的描述，需要接入  `sia-task-hunter`  引用依赖， 有没有不接入  `sia-task-hunter` 的使用方式呢？

![image](https://user-images.githubusercontent.com/29231515/62999303-8eb85280-bea0-11e9-9b39-33dd455eaff1.png)

**Comment by fxbin** [comment]
> 可以啊，开发文档里都有使用方式的描述

开发文档里只有 自动抓取任务开发规则 的描述，需要接入 sia-task-hunter 引用依赖， 有没有不接入 sia-task-hunter 的使用方式呢？
![image](https://user-images.githubusercontent.com/29231515/62999318-9ed03200-bea0-11e9-9965-e808ad5a7a5f.png)

**Comment by TeddiWolf** [comment]
可以啊，可以自己添加HTTP的地址。具体可以在微信群咨询，最下方有微信账号
