### ISSUE TITLE
提问： 是否考虑升级到 SpringBoot 2.1.X & SpringCloud Greenwich SR2 

### ISSUE THREAD

**Issue by fxbin** [siaorg/sia-task#68]

**Comment by TeddiWolf** [comment]
进行中，但目前应该都是靠HTTP进行交互。所以其实相对中心节点都比较独立。稳定压倒一切

**Comment by fxbin** [comment]
> 进行中，但目前应该都是靠HTTP进行交互。所以其实相对中心节点都比较独立。稳定压倒一切

OK， 了解了，因为我们目前项目都是这个版本，在调研的过程中，我就升级到这个版本进行了部分整合与测试

**Comment by TeddiWolf** [comment]
如果高版本发现什么问题，欢迎提给我们

**Comment by fxbin** [comment]
> 如果高版本发现什么问题，欢迎提给我们

好的
